export default function PrivacyPolicy() {
    return (
        <div className="min-h-screen bg-[#2f3136] text-white p-8 font-sans">
            <div className="max-w-4xl mx-auto space-y-6">
                <h1 className="text-4xl font-bold text-[#5865F2] mb-2">Privacy Policy</h1>
                <p className="text-gray-400 text-sm">Last updated: February 07, 2026</p>

                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">Interpretation and Definitions</h2>
                    <h3 className="text-xl font-semibold text-gray-200 mb-2">Interpretation</h3>
                    <p className="mb-4">The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                    <h3 className="text-xl font-semibold text-gray-200 mb-2">Definitions</h3>
                    <p className="mb-2">For the purposes of this Privacy Policy:</p>
                    <ul className="list-disc pl-6 space-y-2 text-gray-300">
                        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Cordis LLC, Los Altos, CA 94024.</li>
                        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                        <li><strong>Country</strong> refers to: California, United States</li>
                        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                        <li><strong>Service</strong> refers to the Website.</li>
                        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                        <li><strong>Website</strong> refers to Discord, accessible from <a href="https://cordis.onthewifi.com" className="text-[#00aff4] hover:underline">https://cordis.onthewifi.com</a>.</li>
                        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">Collecting and Using Your Personal Data</h2>
                    <h3 className="text-xl font-semibold text-gray-200 mb-2">Types of Data Collected</h3>

                    <h4 className="text-lg font-medium text-white mt-4 mb-2">Personal Data</h4>
                    <p className="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <ul className="list-disc pl-6 text-gray-300">
                        <li>Email address</li>
                        <li>First name and last name</li>
                    </ul>

                    <h4 className="text-lg font-medium text-white mt-4 mb-2">Usage Data</h4>
                    <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">Tracking Technologies and Cookies</h2>
                    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">Contact Us</h2>
                    <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                    <ul className="list-disc pl-6 mt-2">
                        <li>By visiting this page on our website: <a href="/contactus" className="text-[#00aff4] hover:underline">Contact Page</a></li>
                    </ul>
                </section>
            </div>
        </div>
    )
}
